/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./features/**/*.{js,jsx,ts,tsx}",
    "./lib/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      spacing: {
        xxs: "8px",
        xs: "16px",
        sm: "20px",
        md: "32px",
        lg: "40px",
        xl: "48px",
        xxl: "56px",
      },
      borderRadius: {
        sm: "4px",
        md: "8px",
        lg: "16px",
        xl: "32px",
        full: "999px",
      },
      colors: {
        // Semantic colors (Tailwind/shadcn convention)
        background: "#101218",
        foreground: "#ffffff",
        card: "#272727",
        "card-foreground": "#ffffff",
        primary: "#000000",
        "primary-foreground": "#ffffff",
        secondary: "#272727",
        "secondary-foreground": "#ffffff",
        muted: "#272727",
        "muted-foreground": "#ffffff",
        accent: "#ffffff",
        "accent-foreground": "#000000",
        border: "#272727",
        input: "#ffffff",
        overlay: "rgba(16, 18, 24, 0.9)",
        separator: "#bdc3c7",
        // Palette colors (avatars, badges, etc.)
        palette: {
          turquoise: "#1abc9c",
          emerald: "#2ecc71",
          "peter-river": "#3498db",
          amethyst: "#9b59b6",
          "wet-asphalt": "#34495e",
          "green-sea": "#16a085",
          nephritis: "#27ae60",
          "belize-hole": "#2980b9",
          wisteria: "#8e44ad",
          "midnight-blue": "#2c3e50",
          sunflower: "#f1c40f",
          carrot: "#e67e22",
          alizarin: "#e74c3c",
          clouds: "#ecf0f1",
          concrete: "#95a5a6",
          orange: "#f39c12",
          pumpkin: "#d35400",
          silver: "#bdc3c7",
          asbestos: "#7f8c8d",
          pomegranate: "#c0392b",
        },
      },
    },
  },
  plugins: [],
};
