export const usTexts = {
  home_tab_movies: "Movies",
  home_tab_series: "Series",
  home_header_title: "Discover",
  home_genre_highlights: "Browse by genre",
  home_trending_title: "Trending today",
  movie_home_now_playing: "Now playing",
  movie_home_popular: "Popular",
  movie_home_top_rated: "Top Rated",
  movie_home_upcoming: "Upcoming",
  movie_details_reviews_title: "Reviews",
  movie_details_companies_title: "Companies",
  movie_details_cast_title: "Cast",
  movie_details_companies_galeria_title: "Gallery",
  movie_details_you_also_may_like: "You may also like",
  movie_details_watch_providers_title: "Where to Watch",
  tv_series_home_airing_today: "Airing Today",
  tv_series_home_on_the_air: "On the Air",
  tv_series_home_popular: "Popular",
  tv_series_home_top_rated: "Top Rated",
  show_more: "Show more",
  search_idle_hint: "Search for movies, TV shows, or people",
  search_recent_title: "Recent",
  search_trending_title: "Trending today",
  search_no_results: "No results for %{query}",
  search_no_filter_matches: "No matches for the selected filters",
  search_error: "Something went wrong. Check your connection and try again.",
  search_retry: "Try again",
  search_filter_all: "All",
  search_filter_movie: "Movies",
  search_filter_tv: "TV",
  search_filter_person: "People",
  search_media_movie: "Movie",
  search_media_tv: "TV",
  search_media_person: "Person",
  search_genres_title: "Genres",
};
