export const usTexts = {
  movie_home_now_playing: "Now playing",
  movie_home_popular: "Popular",
  movie_home_top_rated: "Top Rated",
  movie_home_upcoming: "Upcoming",
  movie_details_reviews_title: "Reviews",
  movie_details_companies_title: "Companies",
  movie_details_cast_title: "Cast",
  movie_details_companies_galeria_title: "Gallery",
  movie_details_you_also_may_like: "You may also like",
  tv_series_home_airing_today: "Airing Today",
  tv_series_home_on_the_air: "On the Air",
  tv_series_home_popular: "Popular",
  tv_series_home_top_rated: "Top Rated",
};
