export const ptBRTexts = {
  movie_home_now_playing: "Em exibição",
  movie_home_popular: "Popular",
  movie_home_top_rated: "Sucessos",
  movie_home_upcoming: "Em breve",
  movie_details_reviews_title: "Avaliações",
  movie_details_companies_title: "Companias",
  movie_details_cast_title: "Elenco",
  movie_details_companies_galeria_title: "Galeria",
  movie_details_you_also_may_like: "Você também pode gostar",
   movie_details_watch_providers_title: "Onde assistir",
  tv_series_home_airing_today: "No ar hoje",
  tv_series_home_on_the_air: "No ar",
  tv_series_home_popular: "Popular",
  tv_series_home_top_rated: "Sucessos",
  show_more: "Ver mais",
};
