export const ptBRTexts = {
  home_tab_movies: "Filmes",
  home_tab_series: "Séries",
  home_header_title: "Descubra",
  home_genre_highlights: "Por gênero",
  home_trending_title: "Em alta hoje",
  movie_home_now_playing: "Em exibição",
  movie_home_popular: "Popular",
  movie_home_top_rated: "Sucessos",
  movie_home_upcoming: "Em breve",
  movie_details_reviews_title: "Avaliações",
  movie_details_companies_title: "Companias",
  movie_details_cast_title: "Elenco",
  movie_details_companies_galeria_title: "Galeria",
  movie_details_you_also_may_like: "Você também pode gostar",
   movie_details_watch_providers_title: "Onde assistir",
  tv_series_home_airing_today: "No ar hoje",
  tv_series_home_on_the_air: "No ar",
  tv_series_home_popular: "Popular",
  tv_series_home_top_rated: "Sucessos",
  show_more: "Ver mais",
  search_idle_hint: "Busque filmes, séries ou pessoas",
  search_recent_title: "Recentes",
  search_trending_title: "Em alta hoje",
  search_no_results: "Nenhum resultado para %{query}",
  search_no_filter_matches: "Nenhum item com os filtros selecionados",
  search_error: "Algo deu errado. Verifique a conexão e tente novamente.",
  search_retry: "Tentar novamente",
  search_filter_all: "Tudo",
  search_filter_movie: "Filmes",
  search_filter_tv: "Séries",
  search_filter_person: "Pessoas",
  search_media_movie: "Filme",
  search_media_tv: "Série",
  search_media_person: "Pessoa",
  search_genres_title: "Gêneros",
};
